version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=imperials
